### ISSUE TITLE
No feed back on what happened after voting for a paper

### ISSUE THREAD

**Issue by Toxicable** [Toxicable/PassPast#25]
When you try vote on a question that you've already voted for you should be told that you have already voted.
Also when you intially vote you shoudl be told it was successful

**Comment by TheFakeAshray** [comment]
Need feedback on what comment you've voted for as well. Perhaps just the green for up arrow, red for down arrow.

As to feed back on what MCQ you voted for, maybe stripped bar, or border around the bar?

**Comment by Toxicable** [comment]
closed as project is not depricated
